name = "my-cloudflare-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# KV Namespaces (key-value store)
[[kv_namespaces]]
binding = "CACHE"
id = "401adb901edc41b1b2b23b7132bd878b"

# D1 Databases (SQLite)
[[d1_databases]]
binding = "DB"
database_name = "tmpd1"
database_id = "124dd7f5-e2b1-4b3c-abac-e8f77f1462c6"

[vars]
APP_ENV = "production"
